version: '3'

networks:
  laravel-blockchain:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-blockchain
    working_dir: /var/www/html
    ports:
      - "8855:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php-blockchain
      - mysql-blockchain
    networks:
      - laravel-blockchain

  mysql-blockchain:
    platform: linux/amd64
    image: mysql:5.7.29
    container_name: mysql-blockchain
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
      MYSQL_ROOT_PASSWORD: root@123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql-blockchain
    networks:
      - laravel-blockchain

  php-blockchain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-blockchain
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    networks:
      - laravel-blockchain

      